name: publish
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
env:
  DO_NOT_TRACK: 1
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write
concurrency: ${{github.workflow}}-${{github.ref}}
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
      - name: 📦 Installing dependencies
        run: pnpm install
      - name: ↗️ Create release
        run: pnpm run release
